# Navigation und sichere Defaults
alias rm='rm -i'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../../'
alias ~='cd ~'
alias -- -='cd -'
alias cdl='dirs -v'
alias p='pushd'
alias o='popd'

alias -- +1='pushd +1'
alias -- +2='pushd +2'
alias -- +3='pushd +3'
alias -- +4='pushd +4'
alias -- -1='pushd -1'
alias -- -2='pushd -2'
alias -- -3='pushd -3'
alias -- -4='pushd -4'
