# Navigation und sichere Defaults
alias rm='rm -i'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../../'
alias ~='cd ~'
alias -- -='cd -'
alias -- -2='cd -2'
alias cdl='dirs -v'
alias p='pushd'
alias o='popd'
